#!/usr/bin/env bash
# installs nginx and configure it to listen on port 80
# print "Hello World"

sudo apt-get -y update
sudo apt-get -y install nginx

# Start nginx and configure it to listen on port 80
sudo service nginx start
sudo sed -i 's/listen\s*80;/listen 80 default_server;/g' /etc/nginx/sites-available/default
sudo service nginx restart

# Create the default HTML page with "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.html
