#!/usr/bin/env bash
# This script Installs Nginx with the following configurations:
#+    Listens on port 80.
#+    Returns a page containing "Hello World" when queried at the root with a curl GET request.
#+    Configures /redirect_me as a "301 Moved Permanently".
#+    A custom 404 page containing "Ceci n'est pas une page".
#+    A custom HTTP header named X-Served-By.
#+    The value of the HTTP header is the hostname of the running server.

# Update package lists and install Nginx
apt-get update
apt-get install -y nginx

# Create directories and files for the web server to serve
mkdir -p /var/www/html
touch /var/www/html/index.html
echo "Hello World" > /var/www/html/index.html
touch /var/www/html/404.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Configure Nginx by modifying the default site configuration file
printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    root   /var/www/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 http://cuberule.com/;
    }

    error_page 404 /404.html;
    location /404 {
      root /var/www/html;
      internal;
    }
}" > /etc/nginx/sites-available/default

# Restart Nginx to apply the new configuration
service nginx restart
