#!/usr/bin/env bash
# script that configures an Ubuntu server with the below requirements
#+ localhost resolves to 127.0.0.2
#+ facebook.com resolves to 8.8.8.8

sudo tee -a /etc/hosts >/dev/null <<EOF
127.0.0.2   localhost
8.8.8.8     facebook.com
EOF

# Restart networking service to apply changes
sudo systemctl restart networking
